name: "Instances"
version: "${version}-${project.build.number}"
main: "org.cyberiantiger.minecraft.instances.Instances"
website: "http://dev.bukkit.org/server-mods/Instances/"
api-version: 1.13
softdepend:
  - Multiverse-Core
  - PermissionsEx
  - Multiverse-Inventories
  - WorldEdit
  - Vault
  - ProtocolLib
commands:
  p:
    description: Chat to your party.
    usage: /<command> <text>
    permission: instances.party
  pme:
    description: Emote to your party.
    usage: /<command> <text>
    permission: instances.party
  pcreate:
    description: Create a party.
    usage: /<command> <party name>
    permission: instances.party
  pdisband:
    description: Disband your party.
    usage: /<command>
    permission: instances.party
  pinfo:
    description: Show information about your party.
    usage: /<command> [<party name>]
    permission: instances.party
  pinvite:
    description: Invite someone to join your party.
    usage: /<command> <player>
    permission: instances.party
  pjoin:
    description: Join a party.
    usage: /<command> <party name>
    permission: instances.party
  pkick:
    description: Kick a member from the party.
    usage: /<command> <player>
    permission: instances.party
  pleader:
    description: Change the party leader.
    usage: /<command> <player>
    permission: instances.party
  pleave:
    description: Leave your party
    usage: /<command>
    permission: instances.party
  puninvite:
    description: Uninvite someone from joining your party.
    usage: /<command> <player>
    permission: instances.party
  plist:
    description: List parties.
    usage: /<command>
    permission: instances.party.list
  home:
    description: Teleport to your home.
    usage: /<command>
    permission: instances.general.home
  sethome:
    description: Set your home.
    usage: /<command>
    permission: instances.general.sethome
  spawn:
    description: Teleport to the spawn location.
    usage: /<command>
    permission: instances.general.spawn
  setspawn:
    description: Set the spawn world.
    usage: /<command> [none]
    permission: instances.general.setspawn
  motd:
    description: Show the motd.
    usage: /<command>
    permission: instances.general.motd
  isave:
    description: Save instance settings.
    usage: /<command>
    permission: instances.general.save
  ireload:
    description: Reload instance settings.
    usage: /<command>
    permission: instances.general.reload
  imob:
    description: Spawn mobs.
    usage: /<command> <type> [<count>]
    permission: instances.general.spawnmob
  igenocide:
    description: Commit genocide.
    usage: /<command> <type> [remove]
    permission: instances.general.genocide
  ispawner:
    description: Modify a spawner's properties.
    usage: |
      /<command> (create|<monster>) [<flags>]
      -d <hand|feet|legs|body|head>:<always|chance> - Set the dropchance of an item, e.g. -d hand:0.5 or -d hand:always (default:0.05)
      -e <max> - Set the number of entities close by required to disable this spawner. (default: 6)
      -f <duration> - Copy your potion effects onto spawned monsters for the specified duration.
      -h <health> - Set the health of the spawned monster.
      -i - Print out information about the spawner.
      -I <head|feet|legs|body|head> - Set the specified item to that which you are currently holding. (default: none)
      -l <true|false> - Set whether spawned monsters can pick up loot. (default: false)
      -L <true|false> - For creepers, spawn them powered or unpowered.
      -m <delay> - Set the minimum delay between spawns. (default: 200)
      -M <delay> - Set the maximum delay between spawns. (default: 800)
      -n <name>|none - Set the custom name for the spawned monster (implies -N true).
      -N <true|false> - Set whether the spawned monster's name is visible.
      -p <range> - Activate when a player is within <range>. (default: 16)
      -P <none|x,y,z> - Set the initial position of the monster, or remove it.
      -r <range> - Range at which to spawn mobs up to (default: 4)
      -s <count> - Set the number of monsters to spawn (default: 4)
      -t <normal|wither> - Set the skeleton type to spawn.
      -T <true|false> - Do not despawn naturally.
      -v <true|false> - Make the spawned monsters invulnerable
      -V <none|x,y,z> - Set the initial motion of the monster, or remove it.
      -z <size> - Set the size of the spawned mob.
      -R <index> - Remove the monster at the specified index from the spawner.
      -S <index> - Select a monster this spawner spawns (default: 0).
      -w <weight> - Set the weight of the currently selected monster.
      -a <monster> - Add a monster to the spawner.
    permission: instances.general.spawner
  icmd:
    description: Set the item in your hand to a command block.
    usage: /<command>
    permission: instances.general.cmd
  iselectiontool:
    description: Set the selection tool to the item you are holding.
    usage: /<command>
    permission: instances.portal.tool
  icreateportal:
    description: Create an instance portal
    usage: /<command> <name>
    permission: instances.portal.create
  isetentrance:
    description: Set the entrance for a portal you are creating.
    usage: /<command>
    permission: instances.portal.create
  isetdestination:
    description: Set the destination for a portal you are creating.
    usage: /<command>
    permission: instances.portal.create
  iportallist:
    description: List all portals.
    usage: /<command>
    permission: instances.portal.list
  ideleteportal:
    description: Delete a portal.
    usage: /<command> <name>
    permission: instances.portal.delete
  imodifyportal:
    description: Modify a portal's properties.
    usage: /<command> <portal> [<set|show|reset> [<property> [<value>]]]
    permission: instances.portal.modify
